(function () {
  const translations = {
    en: {
      "nav.about": "About",
      "nav.skills": "Skills",
      "nav.additionalSkills": "Additional Skills",
      "nav.address": "Address",
      "nav.registration": "Registration",
      "nav.partners": "Partners",
      "nav.contact": "Contact",
      "hero.bannerTitle": "An IT Unicorn in<br><span class=\"highlight\">Hamburg.</span>",
      "hero.bannerText": "Let's explore the world of IT together!",
      "home.aboutEyebrow": "About Me",
      "home.aboutP1": "Enterprise IT Infrastructure professional with 14+ years of experience delivering reliable IT operations across multinational enterprises, government institutions, logistics, hospitality, higher education and telecommunications.",
      "home.aboutP2": "Experienced in enterprise support, Microsoft infrastructure, Linux systems, networking, endpoint management, virtualization and technical leadership.",
      "home.aboutP3": "Recognized for solving complex technical problems, improving operational efficiency and delivering outstanding customer support within SLA-driven environments.",
      "home.register": "Register interest",
      "home.viewAddress": "View address",
      "home.techKicker": "Core Technologies",
      "home.techTitle": "Tools I Work With",
      "home.dialogAddress": "Address",
      "home.dialogAddressText": "21073 Hamburg, Germany",
      "home.dialogAddressSub": "Available for meetings and work opportunities in Hamburg.",
      "home.openMaps": "Open in Maps",
      "home.closeDialog": "Close",
      "home.location": "Hamburg, Germany",
      "home.slideshowTitle": "Welcome to my portfolio!",
      "home.heroName": "Aliyu Awwal, Engr.",
      "home.professionalFocus": "Professional focus",
      "home.heroRole": "Enterprise Infrastructure Engineer",
      "home.tagAdmin": "IT Systems Administrator",
      "home.tagSupport": "IT Support",
      "home.tagField": "Field Engineer",
      "home.tagDataCenter": "Data Center Technician",
      "home.tagPc": "PC Technician",
      "home.tagAllRounder": "All-Rounder",
      "home.introTitle": "Beyond rigorous theories and practical applications",
      "home.introText": "I bring a wealth of experience in enterprise IT infrastructure, with a proven track record of delivering reliable IT operations across multinational enterprises, government institutions, logistics, hospitality, higher education and telecommunications. My expertise spans enterprise support, Microsoft infrastructure, Linux systems, networking, endpoint management, virtualization and technical leadership. I am recognized for solving complex technical problems, improving operational efficiency and delivering outstanding customer support within SLA-driven environments.",
      "home.detailTitle1": "Technology Focus",
      "home.detailText1": "Bridging the gap between cutting-edge technology and real-world applications.",
      "home.detailTitle2": "Multi-Disciplinary Approach",
      "home.detailText2": "Integrating perspectives from multiple fields to address complex technical challenges.",
      "home.detailTitle3": "Job Satisfaction",
      "home.detailText3": "Exploring the factors that contribute to a fulfilling career in technology.",
      "home.skillsKicker": "Skills",
      "home.skillsTitle": "Core Competencies",
      "home.skillsProjectsTitle": "Selected Enterprise Projects",
      "home.skillsProjectsItem1": "Enterprise workstation deployment and lifecycle management.",
      "home.skillsProjectsItem2": "Executive and end-user technical support across hybrid environments.",
      "home.skillsProjectsItem3": "Microsoft 365 onboarding, device provisioning and identity support.",
      "home.skillsProjectsItem4": "Network troubleshooting including DNS, DHCP, VPN and Wi‑Fi.",
      "home.skillsProjectsItem5": "Rack equipment installation, structured cabling and hardware deployment.",
      "home.skillsProjectsItem6": "Technical documentation, asset inventory and knowledge-base development.",
      "home.skillsPlatformsTitle": "Enterprise Platforms",
      "home.skillsPlatformsText": "Supported cloud and enterprise workplace environment across Windows, Linux, macOS and mobile platforms.",
      "home.skillsIdentityTitle": "Enterprise Identity Management",
      "home.skillsIdentityText": "Supported Active Directory, Microsoft 365, Exchange online, Entra ID and endpoint administration.",
      "home.skillsInfraTitle": "Enterprise Infrastructure Administration",
      "home.skillsInfraText": "Servers, Networking, Virtualization, Hardware, Software, Storage, Power, Security, Backup, Monitoring, Scripting and Automation.",
      "home.skillsHardwareTitle": "Enterprise Hardware Deployment",
      "home.skillsHardwareText": "Desktop rollout, Laptop deployment, Electronics Installation, Hardware lifecycle, Asset management, Peripheral support",
      "home.skillsMonitoringTitle": "Monitoring & Troubleshooting",
      "home.skillsMonitoringText": "ELK/Logs, Root Cause Analysis, Incident Management, Problem Solving, Performance Tuning, Hardening",
      "home.skillsTicketingTitle": "Ticketing & Technical Documentation",
      "home.skillsTicketingText": "Ticketing (ServiceNow/ Jira/ OTRS), Documentation (Confluence/ SharePoint), Knowledge Base, SOPs",
      "home.skillsStrengthsTitle": "Professional Strengths",
      "home.skillsStrengthsText": "Known for calm troubleshooting under pressure, excellent communication with technical and non-technical users, structured documentation, ownership of incidents and continuous learning.",
      "home.additionalSkillsKicker": "Additional Skills",
      "home.additionalSkillsTitle": "Practical Experience Beyond IT",
      "home.additionalSkillsIntro": "Beyond the core IT stack, I also bring hands-on experience in logistics, facilities, and operational support, which helps me work effectively in fast-moving environments where reliability and discipline matter just as much as technical knowledge.",
      "home.extraLogisticsTitle": "Logistics & Warehouse Operations",
      "home.extraLogisticsText": "Warehouse handling, stock management, packing, loading and unloading, inventory support, storage organization, and operational coordination in fast-paced environments.",
      "home.extraForkliftTitle": "Forklift & Reach Truck Operations",
      "home.extraForkliftText": "Safe operation of forklifts and reach trucks (schubmaststapler), pallet movement, goods handling, loading procedures, and workplace safety awareness.",
      "home.extraServiceTitle": "Service Technician Support",
      "home.extraServiceText": "On-site diagnostics, preventive checks, equipment servicing, installation support, fault finding, and practical field assistance across technical and operational environments.",
      "home.extraMachineryTitle": "Machinery & Field Support",
      "home.extraMachineryText": "Practical support for machinery operations, equipment handling, maintenance coordination, and on-site assistance in operational and service environments.",
      "home.extraCleaningTitle": "Industrial Cleaning Services",
      "home.extraCleaningText": "Cleaning of indoor and outdoor spaces, offices, homes, commercial buildings, and industrial areas, with emphasis on hygiene, order, and presentation standards.",
      "home.extraFacilitiesTitle": "Hausmeister & Facilities Care",
      "home.extraFacilitiesText": "General building upkeep, cleaning, maintenance support, organizing shared spaces, and contributing to a safe and well-kept environment.",
      "home.extraGardeningTitle": "Gardening & Outdoor Maintenance",
      "home.extraGardeningText": "Lawn care, garden maintenance, basic plant care, outdoor tidying, and upkeep of green spaces to maintain clean and welcoming surroundings.",
      "home.availabilityKicker": "Availability",
      "home.availabilityTitle": "Open to Opportunities",
      "home.availabilityAvailableLabel": "Available",
      "home.availabilityAvailableText": "Immediately available for opportunities.",
      "home.availabilityLocationsLabel": "Locations",
      "home.availabilityLocationsText": "Available for opportunities throughout Germany.",
      "home.availabilityFormatLabel": "Work Format",
      "home.availabilityFormatText": "Available for remote/ on-site/ hybrid opportunities.",
      "home.availabilityAuthorizationLabel": "Work Authorization",
      "home.availabilityAuthorizationText": "Fully authorized to work in Germany.",
      "home.availabilityRelocationLabel": "Relocation",
      "home.availabilityRelocationText": "Open to relocation and remote work opportunities.",
      "home.availabilityInfoLabel": "Additional Info",
      "home.availabilityInfoText": "Open to short practical trial periods.",
      "home.addressKicker": "Address",
      "home.addressTitle": "Hamburg",
      "home.addressText": "21073 Hamburg<br>Germany",
      "home.partnersKicker": "Partners",
      "home.partnersTitle": "Strong Partnerships and Research Network",
      "home.footerTitle": "Enterprise Infrastructure Engineer | All-Rounder",
      "register.kicker": "Registration",
      "register.title": "Register your interest",
      "register.subtitle": "Please, complete the short form below. We will follow up with further details.",
      "register.feesKicker": "Fees",
      "register.feesTitle": "Registration fees",
      "register.feeEmployer": "Potential Employers",
      "register.feeEmployerValue": "0 EUR",
      "register.feeStudents": "Students and researchers",
      "register.feeStudentsValue": "Free",
      "register.feeProfessionals": "Senior professionals &amp; Colleagues",
      "register.feeProfessionalsValue": "0 EUR",
      "register.feePartners": "Partners &amp; Collaborators",
      "register.feePartnersValue": "0 EUR",
      "register.feeOther": "Other",
      "register.feeOtherValue": "Contact for details",
      "register.feeNote": "Fees are concise planning figures and may be confirmed by the team before payment.",
      "register.fullName": "Full name",
      "register.email": "Email",
      "register.affiliation": "Affiliation/Institution/Company",
      "register.category": "Registration category",
      "register.categorySelect": "Select category",
      "register.purpose": "Purpose of Registration",
      "register.purposeSelect": "Select type",
      "register.purposeTalk": "Talk",
      "register.purposeInvitation": "Invitation",
      "register.purposeCollaboration": "Collaboration",
      "register.purposeUndecided": "Undecided",
      "register.titlePurpose": "Title of Purpose (if applicable)",
      "register.fileOne": "Invitation, Contact Information, or Proposal",
      "register.fileOneHelp": "Attach your invitation, contact information, or proposal file.",
      "register.fileTwo": "Evidence of Job Offer/ Proposal/ Payment or Initial Contact",
      "register.fileTwoHelp": "Proof of Job Offer/ Proposal/ Payment or Initial Contact.",
      "register.notes": "Notes",
      "register.notesPlaceholder": "particular needs, requirements, or questions",
      "register.submit": "Submit registration",
      "register.inquiries": "Send inquiries",
      "contact.kicker": "Contact",
      "contact.title": "Send a message",
      "contact.subtitle": "Choose the topic you have questions about.",
      "contact.topic": "Inquiry type",
      "contact.topicSelect": "Select inquiry type",
      "contact.topicGeneral": "General inquiry",
      "contact.topicJobs": "Job Offers",
      "contact.topicRegistration": "Registration inquiry",
      "contact.topicOther": "Other issues",
      "contact.name": "Name",
      "contact.email": "Email",
      "contact.subject": "Subject",
      "contact.message": "Message",
      "contact.submit": "Send inquiry",
      "contact.registerNow": "Register now",
      "contact.panelKicker": "Direct contact",
      "contact.panelTitle": "Email, telephone, address",
      "contact.generalIssues": "General and other issues",
      "contact.registrationIssues": "Registration inquiry",
      "contact.jobOffers": "Job Offers",
      "contact.telephone": "Telephone",
      "contact.addressLabel": "Address",
      "contact.addressText": "Aliyu Awwal<br>21079 Hamburg, Germany"
    },
    de: {
      "nav.about": "Über mich",
      "nav.skills": "Fähigkeiten",
      "nav.additionalSkills": "Zusätzliche Skills",
      "nav.address": "Adresse",
      "nav.registration": "Registrierung",
      "nav.partners": "Partner",
      "nav.contact": "Kontakt",
      "hero.bannerTitle": "Ein IT-Einhorn in<br><span class=\"highlight\">Hamburg.</span>",
      "hero.bannerText": "Lassen Sie uns gemeinsam die Welt der IT entdecken!",
      "home.aboutEyebrow": "Über mich",
      "home.aboutP1": "Enterprise-IT-Infrastruktur-Experte mit 14+ Jahren Erfahrung in der Bereitstellung zuverlässiger IT-Betriebe für multinationales Unternehmen, öffentliche Institutionen, Logistik, Gastronomie, Hochschulbildung und Telekommunikation.",
      "home.aboutP2": "Erfahren in Enterprise Support, Microsoft-Infrastruktur, Linux-Systemen, Netzwerkmanagement, Endpoint-Administration, Virtualisierung und technischer Führung.",
      "home.aboutP3": "Bekannt für die Lösung komplexer technischer Probleme, die Verbesserung der betrieblichen Effizienz und die Bereitstellung erstklassigen Kundenservice in SLA-getriebenen Umgebungen.",
      "home.register": "Interesse anmelden",
      "home.viewAddress": "Adresse anzeigen",
      "home.techKicker": "Kerntechnologien",
      "home.techTitle": "Tools, mit denen ich arbeite",
      "home.dialogAddress": "Adresse",
      "home.dialogAddressText": "21073 Hamburg, Deutschland",
      "home.dialogAddressSub": "Verfügbar für Meetings und berufliche Möglichkeiten in Hamburg.",
      "home.openMaps": "In Maps öffnen",
      "home.closeDialog": "Schließen",
      "home.location": "Hamburg, Deutschland",
      "home.introTitle": "Über rigorose Theorien und praktische Anwendungen",
      "home.introText": "Ich bringe umfangreiche Erfahrung in der IT-Infrastruktur mit und habe nachgewiesen, dass ich zuverlässige IT-Betriebe in multinationalen Unternehmen, öffentlichen Institutionen, Logistik, Hospitality, Hochschulbildung und Telekommunikation bereitstellen kann. Meine Expertise umfasst Enterprise Support, Microsoft-Infrastruktur, Linux-Systeme, Netzwerke, Endpoint-Management, Virtualisierung und technische Leitung. Ich bin bekannt für die Lösung komplexer technischer Probleme, die Verbesserung der Betriebseffizienz und die Bereitstellung exzellentem Kundenservice in SLA-gesteuerten Umgebungen.",
      "home.detailTitle1": "Technologiefokus",
      "home.detailText1": "Die Brücke zwischen modernster Technologie und realen Anwendungen.",
      "home.detailTitle2": "Interdisziplinärer Ansatz",
      "home.detailText2": "Die Kombination verschiedener Perspektiven zur Lösung komplexer technischer Herausforderungen.",
      "home.detailTitle3": "Arbeitszufriedenheit",
      "home.detailText3": "Erforschung der Faktoren, die zu einer erfüllenden Karriere in der Technologie beitragen.",
      "home.skillsKicker": "Fähigkeiten",
      "home.skillsTitle": "Kernkompetenzen",
      "home.additionalSkillsKicker": "Zusätzliche Skills",
      "home.additionalSkillsTitle": "Praktische Erfahrungen jenseits der IT",
      "home.additionalSkillsIntro": "Neben dem Kernbereich IT bringe ich auch praktische Erfahrungen in Logistik, Einrichtungen und operativer Unterstützung mit, die mir helfen, effektiv in schnelllebigen Umgebungen zu arbeiten, in denen Zuverlässigkeit und Disziplin genauso wichtig sind wie technisches Wissen.",
      "home.availabilityKicker": "Verfügbarkeit",
      "home.availabilityTitle": "Offen für Möglichkeiten",
      "home.availabilityAvailableLabel": "Verfügbar",
      "home.availabilityAvailableText": "Sofort verfügbar für neue Möglichkeiten.",
      "home.availabilityLocationsLabel": "Standorte",
      "home.availabilityLocationsText": "Verfügbar für Chancen in ganz Deutschland.",
      "home.availabilityFormatLabel": "Arbeitsformat",
      "home.availabilityFormatText": "Verfügbar für Remote-, Vor-Ort- und Hybrid-Möglichkeiten.",
      "home.availabilityAuthorizationLabel": "Arbeitsberechtigung",
      "home.availabilityAuthorizationText": "Vollständig berechtigt, in Deutschland zu arbeiten.",
      "home.availabilityRelocationLabel": "Umzug",
      "home.availabilityRelocationText": "Offen für Umzug und Remote-Arbeit.",
      "home.availabilityInfoLabel": "Zusätzliche Informationen",
      "home.availabilityInfoText": "Offen für kurze praktische Testphasen.",
      "home.addressKicker": "Adresse",
      "home.addressTitle": "Hamburg",
      "home.addressText": "21073 Hamburg<br>Deutschland",
      "home.partnersKicker": "Partner",
      "home.partnersTitle": "Starke Partnerschaften und Forschungsnetzwerk",
      "home.footerTitle": "Enterprise Infrastructure Engineer | All-Rounder",
      "register.kicker": "Registrierung",
      "register.title": "Interesse anmelden",
      "register.subtitle": "Bitte füllen Sie das kurze Formular unten aus. Wir setzen uns mit weiteren Details in Verbindung.",
      "register.feesKicker": "Gebühren",
      "register.feesTitle": "Registrierungsgebühren",
      "register.feeEmployer": "Potenzielle Arbeitgeber",
      "register.feeEmployerValue": "0 EUR",
      "register.feeStudents": "Studenten und Forscher",
      "register.feeStudentsValue": "Kostenlos",
      "register.feeProfessionals": "Senior-Experten &amp; Kollegen",
      "register.feeProfessionalsValue": "0 EUR",
      "register.feePartners": "Partner &amp; Kollaborateure",
      "register.feePartnersValue": "0 EUR",
      "register.feeOther": "Sonstige",
      "register.feeOtherValue": "Kontaktieren Sie uns für Details",
      "register.feeNote": "Die Gebühren sind grobe Planungswerte und können vor der Zahlung vom Team bestätigt werden.",
      "register.fullName": "Vollständiger Name",
      "register.email": "E-Mail",
      "register.affiliation": "Zugehörigkeit/Institution/Firma",
      "register.category": "Registrierungskategorie",
      "register.categorySelect": "Kategorie auswählen",
      "register.purpose": "Zweck der Registrierung",
      "register.purposeSelect": "Typ auswählen",
      "register.purposeTalk": "Vortrag",
      "register.purposeInvitation": "Einladung",
      "register.purposeCollaboration": "Zusammenarbeit",
      "register.purposeUndecided": "Unentschlossen",
      "register.titlePurpose": "Titel des Zwecks (falls zutreffend)",
      "register.fileOne": "Einladung, Kontaktdaten oder Vorschlag",
      "register.fileOneHelp": "Hängen Sie Ihre Einladung, Kontaktdaten oder Ihren Vorschlag an.",
      "register.fileTwo": "Nachweis für Jobangebot/ Vorschlag/ Zahlung oder ersten Kontakt",
      "register.fileTwoHelp": "Nachweis für Jobangebot/ Vorschlag/ Zahlung oder ersten Kontakt.",
      "register.notes": "Notizen",
      "register.notesPlaceholder": "besondere Bedürfnisse, Anforderungen oder Fragen",
      "register.submit": "Registrierung senden",
      "register.inquiries": "Anfragen senden",
      "contact.kicker": "Kontakt",
      "contact.title": "Nachricht senden",
      "contact.subtitle": "Wählen Sie das Thema aus, zu dem Sie Fragen haben.",
      "contact.topic": "Anfrageart",
      "contact.topicSelect": "Anfrageart auswählen",
      "contact.topicGeneral": "Allgemeine Anfrage",
      "contact.topicJobs": "Jobangebote",
      "contact.topicRegistration": "Registrierungsanfrage",
      "contact.topicOther": "Andere Anliegen",
      "contact.name": "Name",
      "contact.email": "E-Mail",
      "contact.subject": "Betreff",
      "contact.message": "Nachricht",
      "contact.submit": "Anfrage senden",
      "contact.registerNow": "Jetzt registrieren",
      "contact.panelKicker": "Direkter Kontakt",
      "contact.panelTitle": "E-Mail, Telefon, Adresse",
      "contact.generalIssues": "Allgemeine und andere Anliegen",
      "contact.registrationIssues": "Registrierungsanfrage",
      "contact.jobOffers": "Jobangebote",
      "contact.telephone": "Telefon",
      "contact.addressLabel": "Adresse",
      "contact.addressText": "Aliyu Awwal<br>21079 Hamburg, Deutschland"
    },
    fr: {
      "nav.about": "À propos",
      "nav.skills": "Compétences",
      "nav.additionalSkills": "Compétences complémentaires",
      "nav.address": "Adresse",
      "nav.registration": "Inscription",
      "nav.partners": "Partenaires",
      "nav.contact": "Contact",
      "hero.bannerTitle": "Une licorne IT à<br><span class=\"highlight\">Hambourg.</span>",
      "hero.bannerText": "Explorons ensemble le monde de l'informatique !",
      "home.aboutEyebrow": "À propos",
      "home.aboutP1": "Professionnel de l'infrastructure IT d'entreprise avec plus de 14 ans d'expérience dans la mise en place d'opérations TI fiables au sein d'entreprises multinationales, d'institutions publiques, de la logistique, de l'hôtellerie, de l'enseignement supérieur et des télécommunications.",
      "home.aboutP2": "Expérience en assistance d'entreprise, infrastructure Microsoft, systèmes Linux, réseau, gestion des terminaux, virtualisation et leadership technique.",
      "home.aboutP3": "Reconnu pour la résolution de problèmes techniques complexes, l'amélioration de l'efficacité opérationnelle et un service client exceptionnel dans des environnements pilotés par les SLA.",
      "home.register": "S'inscrire",
      "home.viewAddress": "Voir l'adresse",
      "home.techKicker": "Technologies clés",
      "home.techTitle": "Outils que j'utilise",
      "home.dialogAddress": "Adresse",
      "home.dialogAddressText": "21073 Hambourg, Allemagne",
      "home.dialogAddressSub": "Disponible pour des réunions et des opportunités à Hambourg.",
      "home.openMaps": "Ouvrir dans Maps",
      "home.closeDialog": "Fermer",
      "home.location": "Hambourg, Allemagne",
      "home.introTitle": "Au-delà des théories rigoureuses et des applications pratiques",
      "home.introText": "J'apporte une grande expérience dans l'infrastructure informatique d'entreprise et une expérience éprouvée dans la mise en œuvre d'opérations informatiques fiables au sein d'entreprises multinationales, d'institutions publiques, de la logistique, de l'hôtellerie, de l'enseignement supérieur et des télécommunications. Mon expertise couvre le support d'entreprise, l'infrastructure Microsoft, les systèmes Linux, les réseaux, la gestion des terminaux, la virtualisation et le leadership technique. Je suis reconnu pour résoudre des problèmes techniques complexes, améliorer l'efficacité opérationnelle et offrir un service client exceptionnel dans des environnements soumis aux SLA.",
      "home.detailTitle1": "Focus technologique",
      "home.detailText1": "Faire le lien entre la technologie de pointe et les applications du monde réel.",
      "home.detailTitle2": "Approche multidisciplinaire",
      "home.detailText2": "Associer plusieurs perspectives pour relever des défis techniques complexes.",
      "home.detailTitle3": "Satisfaction au travail",
      "home.detailText3": "Explorer les facteurs qui contribuent à une carrière enrichissante dans la technologie.",
      "home.skillsKicker": "Compétences",
      "home.skillsTitle": "Compétences clés",
      "home.additionalSkillsKicker": "Compétences complémentaires",
      "home.additionalSkillsTitle": "Expérience pratique au-delà de l'informatique",
      "home.additionalSkillsIntro": "Au-delà de la pile technologique principale, j'apporte aussi une expérience pratique en logistique, en maintenance d'installations et en soutien opérationnel, ce qui me permet de travailler efficacement dans des environnements dynamiques où la fiabilité et la discipline comptent autant que les connaissances techniques.",
      "home.availabilityKicker": "Disponibilité",
      "home.availabilityTitle": "Ouvert aux opportunités",
      "home.availabilityAvailableLabel": "Disponible",
      "home.availabilityAvailableText": "Disponible immédiatement pour de nouvelles opportunités.",
      "home.availabilityLocationsLabel": "Lieux",
      "home.availabilityLocationsText": "Disponible pour des opportunités partout en Allemagne.",
      "home.availabilityFormatLabel": "Format de travail",
      "home.availabilityFormatText": "Disponible pour des opportunités à distance, sur site ou hybrides.",
      "home.availabilityAuthorizationLabel": "Autorisation de travail",
      "home.availabilityAuthorizationText": "Autorisé à travailler pleinement en Allemagne.",
      "home.availabilityRelocationLabel": "Déménagement",
      "home.availabilityRelocationText": "Ouvert à la mobilité et au travail à distance.",
      "home.availabilityInfoLabel": "Informations supplémentaires",
      "home.availabilityInfoText": "Ouvert à des essais pratiques courts.",
      "home.addressKicker": "Adresse",
      "home.addressTitle": "Hambourg",
      "home.addressText": "21073 Hambourg<br>Allemagne",
      "home.partnersKicker": "Partenaires",
      "home.partnersTitle": "Partenariats solides et réseau de recherche",
      "home.footerTitle": "Ingénieur Infrastructure d'Entreprise | Polyvalent",
      "register.kicker": "Inscription",
      "register.title": "Inscrivez votre intérêt",
      "register.subtitle": "Veuillez remplir le court formulaire ci-dessous. Nous reviendrons vers vous avec plus de détails.",
      "register.feesKicker": "Frais",
      "register.feesTitle": "Frais d'inscription",
      "register.feeEmployer": "Employeurs potentiels",
      "register.feeEmployerValue": "0 EUR",
      "register.feeStudents": "Étudiants et chercheurs",
      "register.feeStudentsValue": "Gratuit",
      "register.feeProfessionals": "Professionnels seniors &amp; collègues",
      "register.feeProfessionalsValue": "0 EUR",
      "register.feePartners": "Partenaires &amp; collaborateurs",
      "register.feePartnersValue": "0 EUR",
      "register.feeOther": "Autre",
      "register.feeOtherValue": "Contactez-nous pour plus de détails",
      "register.feeNote": "Les frais sont des montants de planification et peuvent être confirmés par l'équipe avant le paiement.",
      "register.fullName": "Nom complet",
      "register.email": "E-mail",
      "register.affiliation": "Affiliation/Institution/Entreprise",
      "register.category": "Catégorie d'inscription",
      "register.categorySelect": "Sélectionner une catégorie",
      "register.purpose": "Objet de l'inscription",
      "register.purposeSelect": "Sélectionner un type",
      "register.purposeTalk": "Présentation",
      "register.purposeInvitation": "Invitation",
      "register.purposeCollaboration": "Collaboration",
      "register.purposeUndecided": "Indécis",
      "register.titlePurpose": "Titre de l'objet (si applicable)",
      "register.fileOne": "Invitation, coordonnées ou proposition",
      "register.fileOneHelp": "Ajoutez votre invitation, vos coordonnées ou votre proposition.",
      "register.fileTwo": "Preuve d'offre d'emploi, de proposition, de paiement ou de premier contact",
      "register.fileTwoHelp": "Preuve d'offre d'emploi, de proposition, de paiement ou de premier contact.",
      "register.notes": "Notes",
      "register.notesPlaceholder": "besoins particuliers, exigences ou questions",
      "register.submit": "Soumettre l'inscription",
      "register.inquiries": "Envoyer une demande",
      "contact.kicker": "Contact",
      "contact.title": "Envoyer un message",
      "contact.subtitle": "Choisissez le sujet sur lequel vous avez des questions.",
      "contact.topic": "Type de demande",
      "contact.topicSelect": "Sélectionner le type de demande",
      "contact.topicGeneral": "Demande générale",
      "contact.topicJobs": "Offres d'emploi",
      "contact.topicRegistration": "Demande d'inscription",
      "contact.topicOther": "Autres demandes",
      "contact.name": "Nom",
      "contact.email": "E-mail",
      "contact.subject": "Objet",
      "contact.message": "Message",
      "contact.submit": "Envoyer la demande",
      "contact.registerNow": "S'inscrire maintenant",
      "contact.panelKicker": "Contact direct",
      "contact.panelTitle": "E-mail, téléphone, adresse",
      "contact.generalIssues": "Questions générales et autres",
      "contact.registrationIssues": "Demande d'inscription",
      "contact.jobOffers": "Offres d'emploi",
      "contact.telephone": "Téléphone",
      "contact.addressLabel": "Adresse",
      "contact.addressText": "Aliyu Awwal<br>21079 Hambourg, Allemagne"
    },
    es: {
      "nav.about": "Sobre mí",
      "nav.skills": "Habilidades",
      "nav.additionalSkills": "Habilidades adicionales",
      "nav.address": "Dirección",
      "nav.registration": "Registro",
      "nav.partners": "Socios",
      "nav.contact": "Contacto",
      "hero.bannerTitle": "Un unicornio tecnológico en<br><span class=\"highlight\">Hamburgo.</span>",
      "hero.bannerText": "¡Exploremos juntos el mundo de la tecnología!",
      "home.aboutEyebrow": "Sobre mí",
      "home.aboutP1": "Profesional de infraestructura de TI empresarial con más de 14 años de experiencia entregando operaciones de TI fiables en empresas multinacionales, instituciones gubernamentales, logística, hostelería, educación superior y telecomunicaciones.",
      "home.aboutP2": "Experiencia en soporte empresarial, infraestructura Microsoft, sistemas Linux, redes, gestión de endpoints, virtualización y liderazgo técnico.",
      "home.aboutP3": "Reconocido por resolver problemas técnicos complejos, mejorar la eficiencia operativa y ofrecer un soporte excepcional al cliente en entornos gestionados por SLA.",
      "home.register": "Registrar interés",
      "home.viewAddress": "Ver dirección",
      "home.techKicker": "Tecnologías clave",
      "home.techTitle": "Herramientas con las que trabajo",
      "home.dialogAddress": "Dirección",
      "home.dialogAddressText": "21073 Hamburgo, Alemania",
      "home.dialogAddressSub": "Disponible para reuniones y oportunidades laborales en Hamburgo.",
      "home.openMaps": "Abrir en Maps",
      "home.closeDialog": "Cerrar",
      "home.location": "Hamburgo, Alemania",
      "home.introTitle": "Más allá de teorías rigurosas y aplicaciones prácticas",
      "home.introText": "Aporto una amplia experiencia en infraestructura de TI empresarial y un historial comprobado en la entrega de operaciones de TI fiables en empresas multinacionales, instituciones gubernamentales, logística, hostelería, educación superior y telecomunicaciones. Mi experiencia abarca soporte empresarial, infraestructura Microsoft, sistemas Linux, redes, gestión de endpoints, virtualización y liderazgo técnico. Soy reconocido por resolver problemas técnicos complejos, mejorar la eficiencia operativa y ofrecer un soporte al cliente excepcional en entornos impulsados por SLA.",
      "home.detailTitle1": "Enfoque tecnológico",
      "home.detailText1": "Unir la tecnología de vanguardia con las aplicaciones del mundo real.",
      "home.detailTitle2": "Enfoque multidisciplinario",
      "home.detailText2": "Combinar perspectivas de varios ámbitos para resolver retos técnicos complejos.",
      "home.detailTitle3": "Satisfacción laboral",
      "home.detailText3": "Explorar los factores que contribuyen a una carrera tecnológica gratificante.",
      "home.skillsKicker": "Habilidades",
      "home.skillsTitle": "Competencias principales",
      "home.additionalSkillsKicker": "Habilidades adicionales",
      "home.additionalSkillsTitle": "Experiencia práctica más allá de TI",
      "home.additionalSkillsIntro": "Más allá del núcleo tecnológico, también aporto experiencia práctica en logística, instalaciones y soporte operativo, lo que me permite trabajar eficazmente en entornos dinámicos donde la fiabilidad y la disciplina son igual de importantes que el conocimiento técnico.",
      "home.availabilityKicker": "Disponibilidad",
      "home.availabilityTitle": "Abierto a oportunidades",
      "home.availabilityAvailableLabel": "Disponible",
      "home.availabilityAvailableText": "Disponible de inmediato para oportunidades.",
      "home.availabilityLocationsLabel": "Ubicaciones",
      "home.availabilityLocationsText": "Disponible para oportunidades en toda Alemania.",
      "home.availabilityFormatLabel": "Formato de trabajo",
      "home.availabilityFormatText": "Disponible para oportunidades remotas, presenciales o híbridas.",
      "home.availabilityAuthorizationLabel": "Autorización de trabajo",
      "home.availabilityAuthorizationText": "Autorizado para trabajar plenamente en Alemania.",
      "home.availabilityRelocationLabel": "Reubicación",
      "home.availabilityRelocationText": "Abierto a reubicación y trabajo remoto.",
      "home.availabilityInfoLabel": "Información adicional",
      "home.availabilityInfoText": "Abierto a pruebas prácticas cortas.",
      "home.addressKicker": "Dirección",
      "home.addressTitle": "Hamburgo",
      "home.addressText": "21073 Hamburgo<br>Alemania",
      "home.partnersKicker": "Socios",
      "home.partnersTitle": "Fuertes alianzas y red de investigación",
      "home.footerTitle": "Ingeniero de Infraestructura Empresarial | Polivalente",
      "register.kicker": "Registro",
      "register.title": "Registre su interés",
      "register.subtitle": "Complete el breve formulario a continuación. Nos pondremos en contacto con más detalles.",
      "register.feesKicker": "Tarifas",
      "register.feesTitle": "Tarifas de registro",
      "register.feeEmployer": "Potenciales empleadores",
      "register.feeEmployerValue": "0 EUR",
      "register.feeStudents": "Estudiantes e investigadores",
      "register.feeStudentsValue": "Gratis",
      "register.feeProfessionals": "Profesionales senior &amp; colegas",
      "register.feeProfessionalsValue": "0 EUR",
      "register.feePartners": "Socios &amp; colaboradores",
      "register.feePartnersValue": "0 EUR",
      "register.feeOther": "Otro",
      "register.feeOtherValue": "Póngase en contacto para más detalles",
      "register.feeNote": "Las tarifas son cifras orientativas de planificación y pueden confirmarse con el equipo antes del pago.",
      "register.fullName": "Nombre completo",
      "register.email": "Correo electrónico",
      "register.affiliation": "Afiliación/Institución/Empresa",
      "register.category": "Categoría de registro",
      "register.categorySelect": "Seleccionar categoría",
      "register.purpose": "Motivo del registro",
      "register.purposeSelect": "Seleccionar tipo",
      "register.purposeTalk": "Charla",
      "register.purposeInvitation": "Invitación",
      "register.purposeCollaboration": "Colaboración",
      "register.purposeUndecided": "Indeciso",
      "register.titlePurpose": "Título del motivo (si procede)",
      "register.fileOne": "Invitación, información de contacto o propuesta",
      "register.fileOneHelp": "Adjunte su invitación, información de contacto o propuesta.",
      "register.fileTwo": "Evidencia de oferta de empleo, propuesta, pago o contacto inicial",
      "register.fileTwoHelp": "Prueba de oferta de empleo, propuesta, pago o contacto inicial.",
      "register.notes": "Notas",
      "register.notesPlaceholder": "necesidades concretas, requisitos o preguntas",
      "register.submit": "Enviar registro",
      "register.inquiries": "Enviar consultas",
      "contact.kicker": "Contacto",
      "contact.title": "Enviar un mensaje",
      "contact.subtitle": "Elija el tema sobre el que tiene preguntas.",
      "contact.topic": "Tipo de consulta",
      "contact.topicSelect": "Seleccione el tipo de consulta",
      "contact.topicGeneral": "Consulta general",
      "contact.topicJobs": "Ofertas de empleo",
      "contact.topicRegistration": "Consulta de registro",
      "contact.topicOther": "Otros asuntos",
      "contact.name": "Nombre",
      "contact.email": "Correo electrónico",
      "contact.subject": "Asunto",
      "contact.message": "Mensaje",
      "contact.submit": "Enviar consulta",
      "contact.registerNow": "Registrarse ahora",
      "contact.panelKicker": "Contacto directo",
      "contact.panelTitle": "Correo electrónico, teléfono, dirección",
      "contact.generalIssues": "Consultas generales y otras",
      "contact.registrationIssues": "Consulta de registro",
      "contact.jobOffers": "Ofertas de empleo",
      "contact.telephone": "Teléfono",
      "contact.addressLabel": "Dirección",
      "contact.addressText": "Aliyu Awwal<br>21079 Hamburgo, Alemania"
    },
    pt: {
      "nav.about": "Sobre",
      "nav.skills": "Habilidades",
      "nav.additionalSkills": "Habilidades adicionais",
      "nav.address": "Endereço",
      "nav.registration": "Cadastro",
      "nav.partners": "Parceiros",
      "nav.contact": "Contato",
      "hero.bannerTitle": "Uma lenda da TI em<br><span class=\"highlight\">Hamburgo.</span>",
      "hero.bannerText": "Vamos explorar o mundo da tecnologia juntos!",
      "home.aboutEyebrow": "Sobre mim",
      "home.aboutP1": "Profissional de infraestrutura de TI corporativa com mais de 14 anos de experiência no fornecimento de operações de TI confiáveis em empresas multinacionais, instituições governamentais, logística, hotelaria, educação superior e telecomunicações.",
      "home.aboutP2": "Experiência em suporte corporativo, infraestrutura Microsoft, sistemas Linux, redes, gerenciamento de endpoints, virtualização e liderança técnica.",
      "home.aboutP3": "Reconhecido por resolver problemas técnicos complexos, melhorar a eficiência operacional e entregar um suporte de excelência ao cliente em ambientes orientados por SLA.",
      "home.register": "Registrar interesse",
      "home.viewAddress": "Ver endereço",
      "home.techKicker": "Tecnologias principais",
      "home.techTitle": "Ferramentas com as quais trabalho",
      "home.dialogAddress": "Endereço",
      "home.dialogAddressText": "21073 Hamburgo, Alemanha",
      "home.dialogAddressSub": "Disponível para reuniões e oportunidades em Hamburgo.",
      "home.openMaps": "Abrir no Maps",
      "home.closeDialog": "Fechar",
      "home.location": "Hamburgo, Alemanha",
      "home.introTitle": "Além de teorias rigorosas e aplicações práticas",
      "home.introText": "Trago uma ampla experiência em infraestrutura de TI empresarial, com um histórico comprovado em entregar operações de TI confiáveis em empresas multinacionais, instituições governamentais, logística, hotelaria, educação superior e telecomunicações. Minha experiência abrange suporte empresarial, infraestrutura Microsoft, sistemas Linux, redes, gestão de endpoints, virtualização e liderança técnica. Sou reconhecido por resolver problemas técnicos complexos, melhorar a eficiência operacional e oferecer suporte excepcional ao cliente em ambientes orientados por SLA.",
      "home.detailTitle1": "Foco tecnológico",
      "home.detailText1": "Ligando a tecnologia de ponta às aplicações do mundo real.",
      "home.detailTitle2": "Abordagem multidisciplinar",
      "home.detailText2": "Integrando perspectivas de vários campos para resolver desafios técnicos complexos.",
      "home.detailTitle3": "Satisfação profissional",
      "home.detailText3": "Explorando os fatores que contribuem para uma carreira gratificante na tecnologia.",
      "home.skillsKicker": "Habilidades",
      "home.skillsTitle": "Competências principais",
      "home.additionalSkillsKicker": "Habilidades adicionais",
      "home.additionalSkillsTitle": "Experiência prática além da TI",
      "home.additionalSkillsIntro": "Além da base tecnológica, também trago experiência prática em logística, instalações e suporte operacional, o que me ajuda a atuar com eficiência em ambientes dinâmicos, onde confiabilidade e disciplina importam tanto quanto o conhecimento técnico.",
      "home.availabilityKicker": "Disponibilidade",
      "home.availabilityTitle": "Aberto a oportunidades",
      "home.availabilityAvailableLabel": "Disponível",
      "home.availabilityAvailableText": "Disponível imediatamente para oportunidades.",
      "home.availabilityLocationsLabel": "Locais",
      "home.availabilityLocationsText": "Disponível para oportunidades em toda a Alemanha.",
      "home.availabilityFormatLabel": "Formato de trabalho",
      "home.availabilityFormatText": "Disponível para oportunidades remotas, presenciais ou híbridas.",
      "home.availabilityAuthorizationLabel": "Autorização de trabalho",
      "home.availabilityAuthorizationText": "Totalmente autorizado a trabalhar na Alemanha.",
      "home.availabilityRelocationLabel": "Mudança",
      "home.availabilityRelocationText": "Aberto a mudança de cidade e trabalho remoto.",
      "home.availabilityInfoLabel": "Informações adicionais",
      "home.availabilityInfoText": "Aberto a testes práticos curtos.",
      "home.addressKicker": "Endereço",
      "home.addressTitle": "Hamburgo",
      "home.addressText": "21073 Hamburgo<br>Alemanha",
      "home.partnersKicker": "Parceiros",
      "home.partnersTitle": "Parcerias fortes e rede de pesquisa",
      "home.footerTitle": "Engenheiro de Infraestrutura Empresarial | Multidisciplinar",
      "register.kicker": "Cadastro",
      "register.title": "Registre seu interesse",
      "register.subtitle": "Por favor, preencha o breve formulário abaixo. Entraremos em contato com mais detalhes.",
      "register.feesKicker": "Taxas",
      "register.feesTitle": "Taxas de registro",
      "register.feeEmployer": "Potenciais empregadores",
      "register.feeEmployerValue": "0 EUR",
      "register.feeStudents": "Estudantes e pesquisadores",
      "register.feeStudentsValue": "Grátis",
      "register.feeProfessionals": "Profissionais sêniores &amp; colegas",
      "register.feeProfessionalsValue": "0 EUR",
      "register.feePartners": "Parceiros &amp; colaboradores",
      "register.feePartnersValue": "0 EUR",
      "register.feeOther": "Outro",
      "register.feeOtherValue": "Entre em contato para mais detalhes",
      "register.feeNote": "As taxas são valores de planejamento e podem ser confirmados pela equipe antes do pagamento.",
      "register.fullName": "Nome completo",
      "register.email": "E-mail",
      "register.affiliation": "Afiliação/Instituição/Empresa",
      "register.category": "Categoria de cadastro",
      "register.categorySelect": "Selecione a categoria",
      "register.purpose": "Motivo do cadastro",
      "register.purposeSelect": "Selecione o tipo",
      "register.purposeTalk": "Palestra",
      "register.purposeInvitation": "Convite",
      "register.purposeCollaboration": "Colaboração",
      "register.purposeUndecided": "Indeciso",
      "register.titlePurpose": "Título do motivo (se aplicável)",
      "register.fileOne": "Convite, informações de contato ou proposta",
      "register.fileOneHelp": "Anexe seu convite, informações de contato ou proposta.",
      "register.fileTwo": "Comprovante de oferta de emprego, proposta, pagamento ou contato inicial",
      "register.fileTwoHelp": "Comprovante de oferta de emprego, proposta, pagamento ou contato inicial.",
      "register.notes": "Observações",
      "register.notesPlaceholder": "necessidades específicas, requisitos ou perguntas",
      "register.submit": "Enviar cadastro",
      "register.inquiries": "Enviar consultas",
      "contact.kicker": "Contato",
      "contact.title": "Enviar mensagem",
      "contact.subtitle": "Escolha o tema sobre o qual você tem dúvidas.",
      "contact.topic": "Tipo de consulta",
      "contact.topicSelect": "Selecione o tipo de consulta",
      "contact.topicGeneral": "Consulta geral",
      "contact.topicJobs": "Ofertas de emprego",
      "contact.topicRegistration": "Consulta de cadastro",
      "contact.topicOther": "Outros assuntos",
      "contact.name": "Nome",
      "contact.email": "E-mail",
      "contact.subject": "Assunto",
      "contact.message": "Mensagem",
      "contact.submit": "Enviar consulta",
      "contact.registerNow": "Cadastre-se agora",
      "contact.panelKicker": "Contato direto",
      "contact.panelTitle": "E-mail, telefone, endereço",
      "contact.generalIssues": "Dúvidas gerais e outras",
      "contact.registrationIssues": "Consulta de cadastro",
      "contact.jobOffers": "Ofertas de emprego",
      "contact.telephone": "Telefone",
      "contact.addressLabel": "Endereço",
      "contact.addressText": "Aliyu Awwal<br>21079 Hamburgo, Alemanha"
    },
    ar: {
      "nav.about": "نبذة",
      "nav.skills": "المهارات",
      "nav.additionalSkills": "مهارات إضافية",
      "nav.address": "العنوان",
      "nav.registration": "التسجيل",
      "nav.partners": "الشركاء",
      "nav.contact": "تواصل",
      "hero.bannerTitle": "وحيدتي التقنية في<br><span class=\"highlight\">هامبورغ.</span>",
      "hero.bannerText": "دعنا نستكشف عالم التقنية معًا!",
      "home.aboutEyebrow": "نبذة عني",
      "home.aboutP1": "محترف في بنية تكنولوجيا المعلومات المؤسسية، بخبرة تزيد عن 14 عامًا في تقديم عمليات تكنولوجيا معلومات موثوقة في مؤسسات متعددة الجنسيات، ومؤسسات حكومية، ولوجستيات، وفندقة، وتعليم عالي، وتكنولوجيا الاتصالات.",
      "home.aboutP2": "خبرة في دعم المؤسسات، وبنية Microsoft، وأنظمة Linux، والشبكات، وإدارة نقاط النهاية، والافتراضية، والقيادة التقنية.",
      "home.aboutP3": "معروف بحل المشكلات التقنية المعقدة، وتحسين الكفاءة التشغيلية، وتقديم دعم ممتاز للعملاء في بيئات تعتمد على اتفاقيات مستوى الخدمة.",
      "home.register": "التسجيل",
      "home.viewAddress": "عرض العنوان",
      "home.techKicker": "التقنيات الأساسية",
      "home.techTitle": "الأدوات التي أعمل بها",
      "home.dialogAddress": "العنوان",
      "home.dialogAddressText": "21073 هامبورغ، ألمانيا",
      "home.dialogAddressSub": "متاح للاجتماعات والفرص في هامبورغ.",
      "home.openMaps": "فتح في الخرائط",
      "home.closeDialog": "إغلاق",
      "home.location": "هامبورغ، ألمانيا",
      "home.introTitle": "ما وراء النظريات الدقيقة والتطبيقات العملية",
      "home.introText": "أحمل خبرة واسعة في بنية تكنولوجيا المعلومات المؤسسية، مع سجل مثبت في تقديم عمليات تكنولوجيا معلومات موثوقة في مؤسسات متعددة الجنسيات، ومؤسسات حكومية، ولوجستيات، وفندقة، وتعليم عالي، وتكنولوجيا الاتصالات. تشمل خبرتي دعم المؤسسات، وبنية Microsoft، وأنظمة Linux، والشبكات، وإدارة نقاط النهاية، والافتراضية، والقيادة التقنية. أنا معروف بحل المشكلات التقنية المعقدة، وتحسين الكفاءة التشغيلية، وتقديم دعم ممتاز للعملاء في بيئات تعتمد على اتفاقيات مستوى الخدمة.",
      "home.detailTitle1": "التركيز التكنولوجي",
      "home.detailText1": "ربط أحدث التقنيات بالتطبيقات الواقعية.",
      "home.detailTitle2": "نهج متعدد التخصصات",
      "home.detailText2": "دمج وجهات نظر متعددة لمعالجة التحديات التقنية المعقدة.",
      "home.detailTitle3": "رضا العمل",
      "home.detailText3": "استكشاف العوامل التي تساهم في مسيرة تقنية مُرضية.",
      "home.skillsKicker": "المهارات",
      "home.skillsTitle": "الكفاءات الأساسية",
      "home.additionalSkillsKicker": "مهارات إضافية",
      "home.additionalSkillsTitle": "خبرة عملية تتجاوز IT",
      "home.additionalSkillsIntro": "فوق مكدس التقنية الأساسي، أحمل أيضًا خبرة عملية في اللوجستيات والمرافق والدعم التشغيلي، ما يساعدني على العمل بفعالية في البيئات السريعة الخطى حيث تتساوى الموثوقية والانضباط مع المعرفة التقنية.",
      "home.availabilityKicker": "التوفر",
      "home.availabilityTitle": "مفتوح للفرص",
      "home.availabilityAvailableLabel": "متاح",
      "home.availabilityAvailableText": "متاح فورًا للفرص.",
      "home.availabilityLocationsLabel": "المواقع",
      "home.availabilityLocationsText": "متاح للفرص في جميع أنحاء ألمانيا.",
      "home.availabilityFormatLabel": "صيغة العمل",
      "home.availabilityFormatText": "متاح للفرص عن بُعد أو حضوريًا أو مختلطًا.",
      "home.availabilityAuthorizationLabel": "إذن العمل",
      "home.availabilityAuthorizationText": "مصرح له بالعمل بالكامل في ألمانيا.",
      "home.availabilityRelocationLabel": "إعادة التوطين",
      "home.availabilityRelocationText": "مفتوح لإعادة التوطين والعمل عن بُعد.",
      "home.availabilityInfoLabel": "معلومات إضافية",
      "home.availabilityInfoText": "مفتوح لفترات تجريبية قصيرة.",
      "home.addressKicker": "العنوان",
      "home.addressTitle": "هامبورغ",
      "home.addressText": "21073 هامبورغ<br>ألمانيا",
      "home.partnersKicker": "الشركاء",
      "home.partnersTitle": "شراكات قوية وشبكة بحثية",
      "home.footerTitle": "مهندس البنية المؤسسية | متعدد الجوانب",
      "register.kicker": "التسجيل",
      "register.title": "سجّل اهتمامك",
      "register.subtitle": "يرجى إكمال النموذج القصير أدناه. سنقوم بمراجعة التفاصيل لاحقًا.",
      "register.feesKicker": "الرسوم",
      "register.feesTitle": "رسوم التسجيل",
      "register.feeEmployer": "جهات توظيف محتملة",
      "register.feeEmployerValue": "0 يورو",
      "register.feeStudents": "الطلاب والباحثون",
      "register.feeStudentsValue": "مجاني",
      "register.feeProfessionals": "المحترفون senior &amp; الزملاء",
      "register.feeProfessionalsValue": "0 يورو",
      "register.feePartners": "الشركاء &amp; المتعاونون",
      "register.feePartnersValue": "0 يورو",
      "register.feeOther": "أخرى",
      "register.feeOtherValue": "اتصل للحصول على التفاصيل",
      "register.feeNote": "الرسوم هي أرقام تخطيطية موجزة وقد يتم تأكيدها من قبل الفريق قبل الدفع.",
      "register.fullName": "الاسم الكامل",
      "register.email": "البريد الإلكتروني",
      "register.affiliation": "الانتماء/المؤسسة/الشركة",
      "register.category": "فئة التسجيل",
      "register.categorySelect": "اختر الفئة",
      "register.purpose": "غرض التسجيل",
      "register.purposeSelect": "اختر النوع",
      "register.purposeTalk": "محاضرة",
      "register.purposeInvitation": "دعوة",
      "register.purposeCollaboration": "تعاون",
      "register.purposeUndecided": "غير متأكد",
      "register.titlePurpose": "عنوان الغرض (إن وجد)",
      "register.fileOne": "دعوة أو معلومات الاتصال أو مقترح",
      "register.fileOneHelp": "أرفق دعوتك أو معلومات الاتصال أو اقتراحك.",
      "register.fileTwo": "أدلة عرض العمل/المقترح/الدفع أو الاتصال الأولي",
      "register.fileTwoHelp": "دليل عرض العمل/المقترح/الدفع أو الاتصال الأولي.",
      "register.notes": "ملاحظات",
      "register.notesPlaceholder": "احتياجات محددة أو متطلبات أو أسئلة",
      "register.submit": "إرسال التسجيل",
      "register.inquiries": "إرسال الاستفسارات",
      "contact.kicker": "تواصل",
      "contact.title": "إرسال رسالة",
      "contact.subtitle": "اختر الموضوع الذي لديك أسئلة عنه.",
      "contact.topic": "نوع الاستفسار",
      "contact.topicSelect": "اختر نوع الاستفسار",
      "contact.topicGeneral": "استفسار عام",
      "contact.topicJobs": "عروض العمل",
      "contact.topicRegistration": "استفسار التسجيل",
      "contact.topicOther": "قضايا أخرى",
      "contact.name": "الاسم",
      "contact.email": "البريد الإلكتروني",
      "contact.subject": "الموضوع",
      "contact.message": "الرسالة",
      "contact.submit": "إرسال الاستفسار",
      "contact.registerNow": "سجل الآن",
      "contact.panelKicker": "تواصل مباشر",
      "contact.panelTitle": "البريد الإلكتروني، الهاتف، العنوان",
      "contact.generalIssues": "استفسارات عامة وغيرها",
      "contact.registrationIssues": "استفسار التسجيل",
      "contact.jobOffers": "عروض العمل",
      "contact.telephone": "الهاتف",
      "contact.addressLabel": "العنوان",
      "contact.addressText": "Aliyu Awwal<br>21079 هامبورغ، ألمانيا"
    },
    fa: {
      "nav.about": "درباره من",
      "nav.skills": "مهارت‌ها",
      "nav.additionalSkills": "مهارت‌های اضافی",
      "nav.address": "آدرس",
      "nav.registration": "ثبت نام",
      "nav.partners": "همکاران",
      "nav.contact": "تماس",
      "hero.bannerTitle": "یک شگفت‌نویس فناوری در<br><span class=\"highlight\">هامبورگ.</span>",
      "hero.bannerText": "بیایید با هم جهان فناوری را کشف کنیم!",
      "home.aboutEyebrow": "درباره من",
      "home.aboutP1": "کارشناس زیرساخت فناوری اطلاعات سازمانی با بیش از ۱۴ سال تجربه در ارائه عملیات قابل اعتماد فناوری اطلاعات در شرکت‌های چندملیتی، نهادهای دولتی، لجستیک، هتلداری، آموزش عالی و مخابرات.",
      "home.aboutP2": "تجربه در پشتیبانی سازمانی، زیرساخت مایکروسافت، سیستم‌های لینوکس، شبکه، مدیریت endpoint، مجازی‌سازی و رهبری فنی.",
      "home.aboutP3": "شناخته‌شده برای حل مسائل پیچیده فنی، بهبود بهره‌وری عملیاتی و ارائه خدمات عالی به مشتریان در محیط‌های مبتنی بر SLA.",
      "home.register": "ثبت علاقه",
      "home.viewAddress": "مشاهده آدرس",
      "home.techKicker": "فناوری‌های اصلی",
      "home.techTitle": "ابزارهایی که با آن‌ها کار می‌کنم",
      "home.dialogAddress": "آدرس",
      "home.dialogAddressText": "۲۱۰۷۳ هامبورگ، آلمان",
      "home.dialogAddressSub": "برای جلسات و فرصت‌های شغلی در هامبورگ در دسترس است.",
      "home.openMaps": "باز کردن در نقشه",
      "home.closeDialog": "بستن",
      "home.location": "هامبورگ، آلمان",
      "home.introTitle": "فراتر از نظریه‌های دقیق و کاربردهای عملی",
      "home.introText": "من تجربه گسترده‌ای در زیرساخت فناوری اطلاعات سازمانی دارم و سابقه قابل‌اعتمادی در ارائه عملیات فناوری اطلاعات مطمئن در شرکت‌های چندملیتی، نهادهای دولتی، لجستیک، هتلداری، آموزش عالی و مخابرات دارم. تخصص من در حمایت سازمانی، زیرساخت مایکروسافت، سیستم‌های لینوکس، شبکه، مدیریت endpoint، مجازی‌سازی و رهبری فنی است. من به‌خاطر حل مسائل پیچیده فنی، بهبود بهره‌وری عملیاتی و ارائه خدمات عالی به مشتریان در محیط‌های مبتنی بر SLA شناخته می‌شوم.",
      "home.detailTitle1": "تمرکز فناوری",
      "home.detailText1": "پیوند میان فناوری پیشرفته و کاربردهای دنیای واقعی.",
      "home.detailTitle2": "رویکرد چندرشته‌ای",
      "home.detailText2": "ادغام دیدگاه‌های مختلف برای مقابله با چالش‌های فنی پیچیده.",
      "home.detailTitle3": "رضایت شغلی",
      "home.detailText3": "بررسی عواملی که به یک شغل پُرمعنا در فناوری کمک می‌کنند.",
      "home.skillsKicker": "مهارت‌ها",
      "home.skillsTitle": "مهارت‌های اصلی",
      "home.additionalSkillsKicker": "مهارت‌های اضافی",
      "home.additionalSkillsTitle": "تجربیات عملی فراتر از IT",
      "home.additionalSkillsIntro": "فراتر از پشته اصلی فناوری، تجربه عملی نیز در لجستیک، مراکز، و پشتیبانی عملیاتی دارم که به من کمک می‌کند در محیط‌های پرشتاب، جایی که قابلیت اطمینان و انضباط به اندازه دانش فنی مهم‌اند، مؤثر عمل کنم.",
      "home.availabilityKicker": "در دسترس",
      "home.availabilityTitle": "برای فرصت‌ها باز هستم",
      "home.availabilityAvailableLabel": "در دسترس",
      "home.availabilityAvailableText": "بلافاصله برای فرصت‌ها آماده‌ام.",
      "home.availabilityLocationsLabel": "مناطق",
      "home.availabilityLocationsText": "برای فرصت‌ها در سراسر آلمان در دسترس هستم.",
      "home.availabilityFormatLabel": "فرمت کاری",
      "home.availabilityFormatText": "برای فرصت‌های دورکاری، حضوری و ترکیبی در دسترس هستم.",
      "home.availabilityAuthorizationLabel": "مجوز کاری",
      "home.availabilityAuthorizationText": "کاملاً مجاز به کار در آلمان هستم.",
      "home.availabilityRelocationLabel": "جابجایی",
      "home.availabilityRelocationText": "برای جابجایی و کار از راه دور باز هستم.",
      "home.availabilityInfoLabel": "اطلاعات بیشتر",
      "home.availabilityInfoText": "برای آزمایش‌های کوتاه عملی باز هستم.",
      "home.addressKicker": "آدرس",
      "home.addressTitle": "هامبورگ",
      "home.addressText": "۲۱۰۷۳ هامبورگ<br>آلمان",
      "home.partnersKicker": "همکاران",
      "home.partnersTitle": "هم‌کاری‌های قوی و شبکه پژوهشی",
      "home.footerTitle": "مهندس زیرساخت سازمانی | همه‌کاره",
      "register.kicker": "ثبت نام",
      "register.title": "علاقه‌مند شوید",
      "register.subtitle": "لطفاً فرم کوتاه زیر را تکمیل کنید. ما با جزئیات بیشتر پیگیری می‌کنیم.",
      "register.feesKicker": "هزینه‌ها",
      "register.feesTitle": "هزینه‌های ثبت نام",
      "register.feeEmployer": "کارفرمایان بالقوه",
      "register.feeEmployerValue": "0 یورو",
      "register.feeStudents": "دانشجویان و پژوهشگران",
      "register.feeStudentsValue": "رایگان",
      "register.feeProfessionals": "کارشناسان ارشد &amp; همکاران",
      "register.feeProfessionalsValue": "0 یورو",
      "register.feePartners": "همکاران &amp; مشارکت‌کنندگان",
      "register.feePartnersValue": "0 یورو",
      "register.feeOther": "سایر",
      "register.feeOtherValue": "برای جزئیات با ما تماس بگیرید",
      "register.feeNote": "هزینه‌ها ارقام برنامه‌ریزی کوتاه هستند و ممکن است قبل از پرداخت توسط تیم تأیید شوند.",
      "register.fullName": "نام کامل",
      "register.email": "ایمیل",
      "register.affiliation": "وابستگی/مؤسسه/شرکت",
      "register.category": "دسته ثبت نام",
      "register.categorySelect": "انتخاب دسته",
      "register.purpose": "هدف ثبت نام",
      "register.purposeSelect": "نوع را انتخاب کنید",
      "register.purposeTalk": "سخنرانی",
      "register.purposeInvitation": "دعوت‌نامه",
      "register.purposeCollaboration": "همکاری",
      "register.purposeUndecided": "نامشخص",
      "register.titlePurpose": "عنوان هدف (در صورت وجود)",
      "register.fileOne": "دعوت‌نامه، اطلاعات تماس یا پیشنهاد",
      "register.fileOneHelp": "دعوت‌نامه، اطلاعات تماس یا پیشنهاد خود را ضمیمه کنید.",
      "register.fileTwo": "مدرک پیشنهاد شغلی/پیشنهاد/پرداخت یا تماس اولیه",
      "register.fileTwoHelp": "مدرک پیشنهاد شغلی/پیشنهاد/پرداخت یا تماس اولیه.",
      "register.notes": "یادداشت‌ها",
      "register.notesPlaceholder": "نیازها، الزامات یا سوالات خاص",
      "register.submit": "ثبت نام را ارسال کنید",
      "register.inquiries": "ارسال درخواست‌ها",
      "contact.kicker": "تماس",
      "contact.title": "ارسال پیام",
      "contact.subtitle": "موضوعی را انتخاب کنید که درباره آن سؤال دارید.",
      "contact.topic": "نوع درخواست",
      "contact.topicSelect": "نوع درخواست را انتخاب کنید",
      "contact.topicGeneral": "درخواست عمومی",
      "contact.topicJobs": "پیشنهادهای شغلی",
      "contact.topicRegistration": "درخواست ثبت نام",
      "contact.topicOther": "مسائل دیگر",
      "contact.name": "نام",
      "contact.email": "ایمیل",
      "contact.subject": "موضوع",
      "contact.message": "پیام",
      "contact.submit": "ارسال درخواست",
      "contact.registerNow": "هم‌اکنون ثبت نام کنید",
      "contact.panelKicker": "تماس مستقیم",
      "contact.panelTitle": "ایمیل، تلفن، آدرس",
      "contact.generalIssues": "مسائل عمومی و دیگر",
      "contact.registrationIssues": "درخواست ثبت نام",
      "contact.jobOffers": "پیشنهادهای شغلی",
      "contact.telephone": "تلفن",
      "contact.addressLabel": "آدرس",
      "contact.addressText": "Aliyu Awwal<br>21079 هامبورگ، آلمان"
    },
    pl: {
      "nav.about": "O mnie",
      "nav.skills": "Umiejętności",
      "nav.additionalSkills": "Dodatkowe umiejętności",
      "nav.address": "Adres",
      "nav.registration": "Rejestracja",
      "nav.partners": "Partnerzy",
      "nav.contact": "Kontakt",
      "hero.bannerTitle": "Jednorożec IT w<br><span class=\"highlight\">Hamburgu.</span>",
      "hero.bannerText": "Poznajmy razem świat IT!",
      "home.aboutEyebrow": "O mnie",
      "home.aboutP1": "Specjalista ds. infrastruktury IT przedsiębiorstwa z ponad 14-letnim doświadczeniem w zapewnianiu niezawodnych operacji IT w firmach wielonarodowych, instytucjach rządowych, logistyce, hotelarstwie, szkolnictwie wyższym i telekomunikacji.",
      "home.aboutP2": "Doświadczenie w obsłudze przedsiębiorstw, infrastruktury Microsoft, systemów Linux, sieci, zarządzania punktami końcowymi, wirtualizacji i przywództwa technicznego.",
      "home.aboutP3": "Znany z rozwiązywania złożonych problemów technicznych, poprawy wydajności operacyjnej i zapewniania doskonałej obsługi klienta w środowiskach opartych na SLA.",
      "home.register": "Zarejestruj zainteresowanie",
      "home.viewAddress": "Pokaż adres",
      "home.techKicker": "Kluczowe technologie",
      "home.techTitle": "Narzędzia, z którymi pracuję",
      "home.dialogAddress": "Adres",
      "home.dialogAddressText": "21073 Hamburg, Niemcy",
      "home.dialogAddressSub": "Dostępny na spotkania i możliwości pracy w Hamburgu.",
      "home.openMaps": "Otwórz w Mapach",
      "home.closeDialog": "Zamknij",
      "home.location": "Hamburg, Niemcy",
      "home.introTitle": "Poza rygorystyczną teorią i praktycznymi zastosowaniami",
      "home.introText": "Przynoszę szerokie doświadczenie w infrastrukturze IT przedsiębiorstwa, z udokumentowanym dorobkiem w zapewnianiu niezawodnych operacji IT w firmach wielonarodowych, instytucjach rządowych, logistyce, hotelarstwie, szkolnictwie wyższym i telekomunikacji. Moja specjalizacja obejmuje wsparcie dla przedsiębiorstw, infrastrukturę Microsoft, systemy Linux, sieci, zarządzanie punktami końcowymi, wirtualizację i przywództwo techniczne. Jestem znany z rozwiązywania złożonych problemów technicznych, poprawy wydajności operacyjnej i zapewniania doskonałej obsługi klienta w środowiskach opartych na SLA.",
      "home.detailTitle1": "Skupienie na technologii",
      "home.detailText1": "Łączenie najnowocześniejszych technologii z zastosowaniami w świecie rzeczywistym.",
      "home.detailTitle2": "Podejście wielodyscyplinarne",
      "home.detailText2": "Integracja perspektyw z wielu dziedzin w celu rozwiązywania złożonych problemów technicznych.",
      "home.detailTitle3": "Satysfakcja z pracy",
      "home.detailText3": "Badanie czynników wpływających na satysfakcjonującą karierę w technologii.",
      "home.skillsKicker": "Umiejętności",
      "home.skillsTitle": "Kluczowe kompetencje",
      "home.additionalSkillsKicker": "Dodatkowe umiejętności",
      "home.additionalSkillsTitle": "Doświadczenie praktyczne poza IT",
      "home.additionalSkillsIntro": "Poza podstawowym ekosystemem IT, posiadam również praktyczne doświadczenie w logistyce, utrzymaniu obiektów i wsparciu operacyjnym, co pomaga mi skutecznie działać w dynamicznych środowiskach, w których niezawodność i dyscyplina są równie ważne jak wiedza techniczna.",
      "home.availabilityKicker": "Dostępność",
      "home.availabilityTitle": "Otwartość na możliwości",
      "home.availabilityAvailableLabel": "Dostępny",
      "home.availabilityAvailableText": "Natychmiast dostępny do nowych możliwości.",
      "home.availabilityLocationsLabel": "Lokalizacje",
      "home.availabilityLocationsText": "Dostępny na możliwości w całych Niemczech.",
      "home.availabilityFormatLabel": "Format pracy",
      "home.availabilityFormatText": "Dostępny na opcje zdalne, stacjonarne i hybrydowe.",
      "home.availabilityAuthorizationLabel": "Uprawnienia do pracy",
      "home.availabilityAuthorizationText": "W pełni uprawniony do pracy w Niemczech.",
      "home.availabilityRelocationLabel": "Przeprowadzka",
      "home.availabilityRelocationText": "Otwartość na przeprowadzkę i pracę zdalną.",
      "home.availabilityInfoLabel": "Dodatkowe informacje",
      "home.availabilityInfoText": "Otwartość na krótkie praktyczne okresy próbne.",
      "home.addressKicker": "Adres",
      "home.addressTitle": "Hamburg",
      "home.addressText": "21073 Hamburg<br>Niemcy",
      "home.partnersKicker": "Partnerzy",
      "home.partnersTitle": "Silne partnerstwa i sieć badawcza",
      "home.footerTitle": "Inżynier infrastruktury przedsiębiorstwa | Wszechstronny",
      "register.kicker": "Rejestracja",
      "register.title": "Zarejestruj swoje zainteresowanie",
      "register.subtitle": "Proszę uzupełnić krótki formularz poniżej. Skontaktujemy się z Tobą w celu dalszych szczegółów.",
      "register.feesKicker": "Opłaty",
      "register.feesTitle": "Opłaty rejestracyjne",
      "register.feeEmployer": "Potencjalni pracodawcy",
      "register.feeEmployerValue": "0 EUR",
      "register.feeStudents": "Studenci i badacze",
      "register.feeStudentsValue": "Darmowe",
      "register.feeProfessionals": "Seniorzy &amp; współpracownicy",
      "register.feeProfessionalsValue": "0 EUR",
      "register.feePartners": "Partnerzy &amp; współpracownicy",
      "register.feePartnersValue": "0 EUR",
      "register.feeOther": "Inne",
      "register.feeOtherValue": "Skontaktuj się po szczegóły",
      "register.feeNote": "Opłaty to przybliżone wartości planowania i mogą zostać potwierdzone przez zespół przed płatnością.",
      "register.fullName": "Imię i nazwisko",
      "register.email": "E-mail",
      "register.affiliation": "Afiliacja/Instytucja/Firma",
      "register.category": "Kategoria rejestracji",
      "register.categorySelect": "Wybierz kategorię",
      "register.purpose": "Cel rejestracji",
      "register.purposeSelect": "Wybierz typ",
      "register.purposeTalk": "Wystąpienie",
      "register.purposeInvitation": "Zaproszenie",
      "register.purposeCollaboration": "Współpraca",
      "register.purposeUndecided": "Niepewny",
      "register.titlePurpose": "Tytuł celu (jeśli dotyczy)",
      "register.fileOne": "Zaproszenie, dane kontaktowe lub propozycja",
      "register.fileOneHelp": "Dołącz zaproszenie, dane kontaktowe lub propozycję.",
      "register.fileTwo": "Dowód oferty pracy, propozycji, płatności lub kontaktu początkowego",
      "register.fileTwoHelp": "Dowód oferty pracy, propozycji, płatności lub kontaktu początkowego.",
      "register.notes": "Uwagi",
      "register.notesPlaceholder": "szczególne potrzeby, wymagania lub pytania",
      "register.submit": "Wyślij rejestrację",
      "register.inquiries": "Wyślij zapytania",
      "contact.kicker": "Kontakt",
      "contact.title": "Wyślij wiadomość",
      "contact.subtitle": "Wybierz temat, który Cię interesuje.",
      "contact.topic": "Typ zapytania",
      "contact.topicSelect": "Wybierz typ zapytania",
      "contact.topicGeneral": "Zapytanie ogólne",
      "contact.topicJobs": "Oferty pracy",
      "contact.topicRegistration": "Zapytanie o rejestrację",
      "contact.topicOther": "Inne sprawy",
      "contact.name": "Imię",
      "contact.email": "E-mail",
      "contact.subject": "Temat",
      "contact.message": "Wiadomość",
      "contact.submit": "Wyślij zapytanie",
      "contact.registerNow": "Zarejestruj się teraz",
      "contact.panelKicker": "Kontakt bezpośredni",
      "contact.panelTitle": "E-mail, telefon, adres",
      "contact.generalIssues": "Zapytania ogólne i inne",
      "contact.registrationIssues": "Zapytanie o rejestrację",
      "contact.jobOffers": "Oferty pracy",
      "contact.telephone": "Telefon",
      "contact.addressLabel": "Adres",
      "contact.addressText": "Aliyu Awwal<br>21079 Hamburg, Niemcy"
    },
    hi: {
      "nav.about": "मेरे बारे में",
      "nav.skills": "कौशल",
      "nav.additionalSkills": "अतिरिक्त कौशल",
      "nav.address": "पता",
      "nav.registration": "पंजीकरण",
      "nav.partners": "भागीदार",
      "nav.contact": "संपर्क",
      "hero.bannerTitle": "आईटी का एक यूनिकॉर्न<br><span class=\"highlight\">हैम्बर्ग में.</span>",
      "hero.bannerText": "आइए मिलकर IT की दुनिया का पता लगाएँ!",
      "home.aboutEyebrow": "मेरे बारे में",
      "home.aboutP1": "एंटरप्राइज़ IT इन्फ्रास्ट्रक्चर प्रोफेशनल, 14+ वर्षों के अनुभव के साथ, मल्टीनेशनल एंटरप्राइज़, सरकारी संस्थानों, लॉजिस्टिक्स, हॉस्पिटैलिटी, उच्च शिक्षा और टेलीकम्युनिकेशन में विश्वसनीय IT संचालन उपलब्ध कराता है।",
      "home.aboutP2": "एंटरप्राइज़ सपोर्ट, Microsoft इन्फ्रास्ट्रक्चर, Linux सिस्टम, नेटवर्किंग, एंडपॉइंट प्रबंधन, वर्चुअलाइज़ेशन और टेक्निकल लीडरशिप में अनुभव।",
      "home.aboutP3": "जटिल तकनीकी समस्याओं को हल करने, परिचालन दक्षता में सुधार और SLA-आधारित वातावरण में उत्कृष्ट ग्राहक सहायता देने के लिए पहचाना जाता है।",
      "home.register": "रजिस्टर करें",
      "home.viewAddress": "पता देखें",
      "home.techKicker": "मुख्य तकनीकें",
      "home.techTitle": "वे टूल जिनसे मैं काम करता हूँ",
      "home.dialogAddress": "पता",
      "home.dialogAddressText": "21073 हैम्बर्ग, जर्मनी",
      "home.dialogAddressSub": "हैम्बर्ग में मीटिंग और अवसरों के लिए उपलब्ध।",
      "home.openMaps": "मैप्स में खोलें",
      "home.closeDialog": "बंद करें",
      "home.location": "हैम्बर्ग, जर्मनी",
      "home.introTitle": "सख्त सिद्धांतों और व्यावहारिक अनुप्रयोगों से आगे",
      "home.introText": "मैं एंटरप्राइज़ IT इन्फ्रास्ट्रक्चर में व्यापक अनुभव लेकर आता हूँ और मल्टीनेशनल एंटरप्राइज़, सरकारी संस्थानों, लॉजिस्टिक्स, हॉस्पिटैलिटी, उच्च शिक्षा और टेलीकम्युनिकेशन में विश्वसनीय IT संचालन प्रदान करने का प्रमाणित ट्रैक रिकॉर्ड रखता हूँ। मेरी विशेषज्ञता में एंटरप्राइज़ सपोर्ट, Microsoft इन्फ्रास्ट्रक्चर, Linux सिस्टम, नेटवर्किंग, एंडपॉइंट प्रबंधन, वर्चुअलाइज़ेशन और टेक्निकल लीडरशिप शामिल है। मुझे जटिल तकनीकी समस्याओं को हल करने, परिचालन दक्षता में सुधार और SLA-आधारित वातावरण में उत्कृष्ट ग्राहक सहायता प्रदान करने के लिए पहचाना जाता है।",
      "home.detailTitle1": "तकनीकी फोकस",
      "home.detailText1": "अत्याधुनिक तकनीक को वास्तविक दुनिया के अनुप्रयोगों से जोड़ना।",
      "home.detailTitle2": "मल्टी-डिसिप्लिनरी दृष्टिकोण",
      "home.detailText2": "जटिल तकनीकी चुनौतियों को हल करने के लिए कई क्षेत्रों की दृष्टियों को एक साथ लाना।",
      "home.detailTitle3": "नौकरी संतुष्टि",
      "home.detailText3": "ऐसे कारकों की खोज करना जो तकनीक में संतोषजनक करियर में योगदान करते हैं।",
      "home.skillsKicker": "कौशल",
      "home.skillsTitle": "मुख्य दक्षताएँ",
      "home.additionalSkillsKicker": "अतिरिक्त कौशल",
      "home.additionalSkillsTitle": "IT के बाहर व्यावहारिक अनुभव",
      "home.additionalSkillsIntro": "मुख्य IT स्टैक के अलावा, मेरे पास लॉजिस्टिक्स, सुविधाओं और परिचालन सहयोग में भी व्यावहारिक अनुभव है, जो मुझे तेज़-तर्रार वातावरण में प्रभावी ढंग से काम करने में मदद करता है जहाँ विश्वसनीयता और अनुशासन तकनीकी ज्ञान जितना ही महत्वपूर्ण है।",
      "home.availabilityKicker": "उपलब्धता",
      "home.availabilityTitle": "अवसरों के लिए खुला",
      "home.availabilityAvailableLabel": "उपलब्ध",
      "home.availabilityAvailableText": "अवसरों के लिए तुरंत उपलब्ध।",
      "home.availabilityLocationsLabel": "स्थान",
      "home.availabilityLocationsText": "सभी जर्मनी में अवसरों के लिए उपलब्ध।",
      "home.availabilityFormatLabel": "कार्य प्रारूप",
      "home.availabilityFormatText": "रिमोट, ऑन-साइट और हाइब्रिड अवसरों के लिए उपलब्ध।",
      "home.availabilityAuthorizationLabel": "कार्यकरण",
      "home.availabilityAuthorizationText": "जर्मनी में काम करने के लिए पूरी तरह अधिकृत।",
      "home.availabilityRelocationLabel": "स्थानांतरण",
      "home.availabilityRelocationText": "स्थानांतरण और रिमोट कार्य के लिए खुला।",
      "home.availabilityInfoLabel": "अतिरिक्त जानकारी",
      "home.availabilityInfoText": "कम अवधि के व्यावहारिक परीक्षण के लिए खुला।",
      "home.addressKicker": "पता",
      "home.addressTitle": "हैम्बर्ग",
      "home.addressText": "21073 हैम्बर्ग<br>जर्मनी",
      "home.partnersKicker": "भागीदार",
      "home.partnersTitle": "मजबूत साझेदारी और अनुसंधान नेटवर्क",
      "home.footerTitle": "एंटरप्राइज़ इन्फ्रास्ट्रक्चर इंजीनियर | ऑल-राउंडर",
      "register.kicker": "पंजीकरण",
      "register.title": "अपना Interesse रजिस्टर करें",
      "register.subtitle": "कृपया नीचे दिए गए छोटे फॉर्म को भरें। हम आगे की जानकारी के साथ संपर्क करेंगे।",
      "register.feesKicker": "शुल्क",
      "register.feesTitle": "पंजीकरण शुल्क",
      "register.feeEmployer": "संभावित नियोक्ता",
      "register.feeEmployerValue": "0 EUR",
      "register.feeStudents": "विद्यार्थी और शोधकर्ता",
      "register.feeStudentsValue": "मुफ़्त",
      "register.feeProfessionals": "वरिष्ठ पेशेवर &amp; सहयोगी",
      "register.feeProfessionalsValue": "0 EUR",
      "register.feePartners": "भागीदार &amp; सहयोगी",
      "register.feePartnersValue": "0 EUR",
      "register.feeOther": "अन्य",
      "register.feeOtherValue": "विवरण के लिए संपर्क करें",
      "register.feeNote": "शुल्क योजना के संक्षिप्त आंकड़े हैं और भुगतान से पहले टीम द्वारा पुष्टि की जा सकती है।",
      "register.fullName": "पूरा नाम",
      "register.email": "ईमेल",
      "register.affiliation": "संबद्धता/संस्थान/कंपनी",
      "register.category": "पंजीकरण श्रेणी",
      "register.categorySelect": "श्रेणी चुनें",
      "register.purpose": "पंजीकरण का उद्देश्य",
      "register.purposeSelect": "प्रकार चुनें",
      "register.purposeTalk": "भाषण",
      "register.purposeInvitation": "आमंत्रण",
      "register.purposeCollaboration": "सहयोग",
      "register.purposeUndecided": "अविचारित",
      "register.titlePurpose": "उद्देश्य का शीर्षक (यदि लागू हो)",
      "register.fileOne": "आमंत्रण, संपर्क जानकारी या प्रस्ताव",
      "register.fileOneHelp": "अपना आमंत्रण, संपर्क जानकारी या प्रस्ताव संलग्न करें।",
      "register.fileTwo": "नौकरी ऑफर/प्रस्ताव/भुगतान या प्रारंभिक संपर्क का प्रमाण",
      "register.fileTwoHelp": "नौकरी ऑफर/प्रस्ताव/भुगतान या प्रारंभिक संपर्क का प्रमाण।",
      "register.notes": "नोट्स",
      "register.notesPlaceholder": "विशिष्ट आवश्यकताएँ, आवश्यकताएँ या प्रश्न",
      "register.submit": "पंजीकरण जमा करें",
      "register.inquiries": "पूछताछ भेजें",
      "contact.kicker": "संपर्क",
      "contact.title": "संदेश भेजें",
      "contact.subtitle": "उस विषय का चयन करें जिसके बारे में आपके प्रश्न हैं।",
      "contact.topic": "पूछताछ प्रकार",
      "contact.topicSelect": "पूछताछ प्रकार चुनें",
      "contact.topicGeneral": "सामान्य पूछताछ",
      "contact.topicJobs": "नौकरी के अवसर",
      "contact.topicRegistration": "पंजीकरण पूछताछ",
      "contact.topicOther": "अन्य मुद्दे",
      "contact.name": "नाम",
      "contact.email": "ईमेल",
      "contact.subject": "विषय",
      "contact.message": "संदेश",
      "contact.submit": "पूछताछ भेजें",
      "contact.registerNow": "अभी पंजीकरण करें",
      "contact.panelKicker": "प्रत्यक्ष संपर्क",
      "contact.panelTitle": "ईमेल, टेलीफोन, पता",
      "contact.generalIssues": "सामान्य और अन्य मुद्दे",
      "contact.registrationIssues": "पंजीकरण पूछताछ",
      "contact.jobOffers": "नौकरी के अवसर",
      "contact.telephone": "टेलीफोन",
      "contact.addressLabel": "पता",
      "contact.addressText": "Aliyu Awwal<br>21079 हैम्बर्ग, जर्मनी"
    }
  };

  const languageSwitcher = document.getElementById("language-switcher");
  const defaultLanguage = "en";

  function getStoredLanguage() {
    try {
      return localStorage.getItem("portfolio-language") || defaultLanguage;
    } catch (error) {
      return defaultLanguage;
    }
  }

  function setStoredLanguage(language) {
    try {
      localStorage.setItem("portfolio-language", language);
    } catch (error) {
      // Ignore storage errors in local preview mode.
    }
  }

  function applyTranslations(language) {
    const currentLanguage = translations[language] ? language : defaultLanguage;
    const languagePack = translations[currentLanguage];
    const fallbackPack = translations[defaultLanguage];
    const isRtl = currentLanguage === "ar" || currentLanguage === "fa";

    document.documentElement.lang = currentLanguage;
    document.documentElement.dir = isRtl ? "rtl" : "ltr";
    document.body.classList.toggle("rtl-layout", isRtl);

    document.querySelectorAll("[data-i18n]").forEach((element) => {
      const key = element.dataset.i18n;
      const value = languagePack[key] || fallbackPack[key];
      if (!value) {
        return;
      }
      element.innerHTML = value;
    });

    if (languageSwitcher) {
      languageSwitcher.value = currentLanguage;
    }

    setStoredLanguage(currentLanguage);
  }

  if (languageSwitcher) {
    const savedLanguage = getStoredLanguage();
    languageSwitcher.addEventListener("change", (event) => {
      applyTranslations(event.target.value);
    });
    applyTranslations(savedLanguage);
  }

  const themeToggle = document.getElementById("theme-toggle");
  const themeLabel = themeToggle ? themeToggle.querySelector(".theme-toggle-label") : null;

  const getStoredTheme = () => {
    try {
      return localStorage.getItem("portfolio-theme");
    } catch (error) {
      return null;
    }
  };

  const setStoredTheme = (theme) => {
    try {
      localStorage.setItem("portfolio-theme", theme);
    } catch (error) {
      // Ignore storage errors for local file previews.
    }
  };

  const applyTheme = (theme) => {
    const isDark = theme === "dark";
    document.body.classList.toggle("theme-dark", isDark);
    if (themeToggle) {
      themeToggle.setAttribute("aria-pressed", String(isDark));
      themeToggle.setAttribute("aria-label", isDark ? "Switch to light mode" : "Switch to dark mode");
      if (themeLabel) {
        themeLabel.textContent = isDark ? "Light mode" : "Dark mode";
      }
    }
    setStoredTheme(theme);
  };

  const savedTheme = getStoredTheme();
  const prefersDark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
  applyTheme(savedTheme || (prefersDark ? "dark" : "light"));

  if (themeToggle) {
    const handleThemeToggle = () => {
      const nextTheme = document.body.classList.contains("theme-dark") ? "light" : "dark";
      applyTheme(nextTheme);
    };

    themeToggle.addEventListener("click", handleThemeToggle);
    themeToggle.onclick = handleThemeToggle;
  }

  const addressDialog = document.getElementById("address-dialog");
  const addressTrigger = document.querySelector("[data-address-trigger]");
  const addressClose = document.querySelector("[data-address-close]");

  if (addressTrigger && addressDialog) {
    addressTrigger.addEventListener("click", () => {
      if (typeof addressDialog.showModal === "function") {
        addressDialog.showModal();
      } else {
        window.alert("21073 Hamburg, Germany");
      }
    });
  }

  if (addressClose && addressDialog) {
    addressClose.addEventListener("click", () => {
      addressDialog.close();
    });
  }

  if (addressDialog) {
    addressDialog.addEventListener("click", (event) => {
      if (event.target === addressDialog) {
        addressDialog.close();
      }
    });
  }

  const slideshow = document.getElementById("slideshow");
  if (!slideshow) {
    return;
  }

  const slides = Array.from(slideshow.querySelectorAll(".slide"));
  const prevButton = slideshow.querySelector(".slide-btn.prev");
  const nextButton = slideshow.querySelector(".slide-btn.next");
  const dotsContainer = slideshow.querySelector("#slide-dots");

  if (!slides.length) {
    return;
  }

  let activeIndex = 0;
  let autoplayTimer = null;

  function setActiveSlide(nextIndex) {
    activeIndex = (nextIndex + slides.length) % slides.length;

    slides.forEach((slide, index) => {
      const isActive = index === activeIndex;
      slide.classList.toggle("active", isActive);
      slide.setAttribute("aria-hidden", String(!isActive));
    });

    if (dotsContainer) {
      const dots = Array.from(dotsContainer.querySelectorAll(".slide-dot"));
      dots.forEach((dot, index) => {
        const isActive = index === activeIndex;
        dot.classList.toggle("active", isActive);
        dot.setAttribute("aria-current", isActive ? "true" : "false");
      });
    }
  }

  function showNextSlide() {
    setActiveSlide(activeIndex + 1);
  }

  function showPreviousSlide() {
    setActiveSlide(activeIndex - 1);
  }

  function startAutoplay() {
    stopAutoplay();
    autoplayTimer = window.setInterval(showNextSlide, 6000);
  }

  function stopAutoplay() {
    if (autoplayTimer !== null) {
      window.clearInterval(autoplayTimer);
      autoplayTimer = null;
    }
  }

  if (dotsContainer) {
    dotsContainer.innerHTML = "";

    slides.forEach((_, index) => {
      const button = document.createElement("button");
      button.type = "button";
      button.className = "slide-dot";
      button.setAttribute("aria-label", "Go to slide " + (index + 1));
      button.addEventListener("click", () => {
        setActiveSlide(index);
        startAutoplay();
      });
      dotsContainer.appendChild(button);
    });
  }

  if (prevButton) {
    prevButton.addEventListener("click", () => {
      showPreviousSlide();
      startAutoplay();
    });
  }

  if (nextButton) {
    nextButton.addEventListener("click", () => {
      showNextSlide();
      startAutoplay();
    });
  }

  slideshow.addEventListener("mouseenter", stopAutoplay);
  slideshow.addEventListener("mouseleave", startAutoplay);
  slideshow.addEventListener("focusin", stopAutoplay);
  slideshow.addEventListener("focusout", startAutoplay);

  setActiveSlide(0);
  startAutoplay();
})();
